apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  selector:
    app: python-api
  type: {{ .Values.fastapi.service.type }}
  ports:
    - port: {{ .Values.fastapi.service.port }}
      targetPort: {{ .Values.fastapi.service.targetPort }}