apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: {{ .Values.fastapi.replicaCount }}
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: "{{ .Values.fastapi.image.repository }}:{{ .Values.fastapi.image.tag }}"
          imagePullPolicy: {{ .Values.fastapi.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fastapi.service.targetPort }}
          envFrom:
            - configMapRef:
                name: redis-cm
            - secretRef:
                name: redis-secret